name: Main

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}@main-${{ github.ref }}
  cancel-in-progress: true

jobs:

  infos:
    name: Infos
    runs-on: ubuntu-22.04
    outputs:
      package-namespace: ${{ steps.infos.outputs.namespace }}
    steps:
      - name: Some infos
        id: infos
        run: |
          echo github.run_id is ${{ github.run_id }}
          echo github.ref is ${{ github.ref }}
          echo github.head_ref is ${{ github.head_ref }}
          echo github.ref_name is ${{ github.ref_name }}
          echo github.sha is ${{ github.sha }}
          echo github.event_name is ${{ github.event_name }}
          echo github.event.pull_request.user.login is ${{ github.event.pull_request.user.login }}
          echo github.event.action is ${{ github.event.action }}
          echo github.event.repository_owner is ${{ github.repository_owner }}
          NAMESPACE=${{ github.repository || github.event.repository }}
          NAMESPACE_LC=${NAMESPACE,,}
          echo "namespace=${NAMESPACE_LC}" >> $GITHUB_OUTPUT
          echo namespace is ${NAMESPACE_LC}

  build_rpi:
    name: Build Rpi
    needs:
      - infos
    uses: ./.github/workflows/build-rpi.yml
    secrets: inherit
    with:
      namespace: ${{ needs.infos.outputs.package-namespace }}
      project_ref: ''
      subproject_sha: ''
      artifact_name: senscord-edc-rpi-deb-${{ github.run_id }}

  checkpoint_success:
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    needs:
      - build_rpi
    steps:
      - name: Check all previous jobs finished correctly
        run: |
          SUCCESS=true

          if [[ "${{ needs.build_rpi.result }}" != "success" ]]; then
            echo "RPi build failed"
            SUCCESS=false
          else
            echo "RPi build succeeded"
          fi

          if [[ "$SUCCESS" == "true" ]]; then
            echo "All required checks passed. This PR can be merged"
          else
            echo "Required checks failed. This PR cannot be merged"
            exit 1
          fi
